//! Integration tests for the hif CLI.
//!
//! These tests verify the CLI works correctly from an end-user perspective.

use assert_cmd::Command;
use predicates::prelude::*;

/// Get a command for the hif binary.
fn hif() -> Command {
    Command::cargo_bin("hif").unwrap()
}

// =============================================================================
// Help and Version Tests
// =============================================================================

#[test]
fn cli_shows_help() {
    hif()
        .arg("--help")
        .assert()
        .success()
        .stdout(predicate::str::contains("hif CLI"))
        .stdout(predicate::str::contains("Usage:"))
        .stdout(predicate::str::contains("auth"))
        .stdout(predicate::str::contains("repository"))
        .stdout(predicate::str::contains("session"));
}

#[test]
fn cli_shows_version() {
    hif()
        .arg("--version")
        .assert()
        .success()
        .stdout(predicate::str::contains("hif"));
}

#[test]
fn subcommand_help_works() {
    hif()
        .args(["auth", "--help"])
        .assert()
        .success()
        .stdout(predicate::str::contains("login"))
        .stdout(predicate::str::contains("status"))
        .stdout(predicate::str::contains("logout"));
}

#[test]
fn usage_spec_outputs_kdl() {
    hif()
        .arg("--usage-spec")
        .assert()
        .success()
        .stdout(predicate::str::contains(
            "// @generated by usage-cli from clap metadata",
        ))
        .stdout(predicate::str::contains("bin hif"))
        .stdout(predicate::str::contains("cmd auth"))
        .stdout(predicate::str::contains("cmd repository"));
}

#[test]
fn usage_spec_is_hidden_from_help() {
    hif()
        .arg("--help")
        .assert()
        .success()
        .stdout(predicate::str::contains("--usage-spec").not());
}

#[test]
fn commands_persist_diagnostics_session() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .arg("status")
        .assert()
        .failure()
        .stderr(predicate::str::contains("No workspace"));

    let state_dir = temp_dir.path().join("state");
    let sessions_dir = state_dir.join("sessions");
    let entries: Vec<_> = std::fs::read_dir(&sessions_dir)
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .collect();

    assert_eq!(entries.len(), 1);
    let session_dir = &entries[0];
    assert!(session_dir.join("session.json").exists());
    assert!(session_dir.join("verbose.log").exists());
    assert!(session_dir.join("network.har").exists());
    assert!(session_dir.join("grpc.jsonl").exists());

    let session: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(session_dir.join("session.json")).unwrap())
            .unwrap();
    assert_eq!(session["exit_code"], 1);
    assert_eq!(session["output_mode"], "human");

    let latest = std::fs::read_to_string(state_dir.join("latest-session")).unwrap();
    assert!(latest.contains(session_dir.file_name().unwrap().to_str().unwrap()));
}

#[test]
fn debug_latest_reads_previous_session() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .arg("status")
        .assert()
        .failure()
        .stderr(predicate::str::contains("No workspace"));

    let first_session = std::fs::read_to_string(temp_dir.path().join("state/latest-session"))
        .unwrap()
        .lines()
        .next()
        .unwrap()
        .to_string();

    let assert = hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["debug", "latest", "--format", "json"])
        .assert()
        .success();

    let stdout = String::from_utf8(assert.get_output().stdout.clone()).unwrap();
    let payload: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    assert_eq!(payload["status"], "ok");
    assert_eq!(payload["action"], "debug.latest");
    assert_eq!(payload["data"]["id"], first_session);

    let latest_after = std::fs::read_to_string(temp_dir.path().join("state/latest-session"))
        .unwrap()
        .lines()
        .next()
        .unwrap()
        .to_string();
    assert_ne!(latest_after, first_session);
}

#[test]
fn debug_defaults_skip_debug_sessions() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .arg("status")
        .assert()
        .failure();

    let first_session = std::fs::read_to_string(temp_dir.path().join("state/latest-session"))
        .unwrap()
        .lines()
        .next()
        .unwrap()
        .to_string();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .arg("debug")
        .arg("latest")
        .assert()
        .success();

    let assert = hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["debug", "requests", "--format", "json"])
        .assert()
        .success();

    let stdout = String::from_utf8(assert.get_output().stdout.clone()).unwrap();
    let payload: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    assert_eq!(payload["data"]["session_id"], first_session);
}

// =============================================================================
// Auth Status Tests
// =============================================================================

#[test]
fn auth_status_when_not_logged_in() {
    // Use a temp directory for config to avoid affecting real config
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["auth", "status"])
        .assert()
        .success()
        .stdout(predicate::str::contains("warning: Not logged in."))
        .stdout(predicate::str::contains("Run"));
}

#[test]
fn auth_logout_when_not_logged_in() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["auth", "logout"])
        .assert()
        .success()
        .stdout(predicate::str::contains("Logged out."));
}

// =============================================================================
// Workspace Tests
// =============================================================================

#[test]
fn status_outside_workspace() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .current_dir(temp_dir.path())
        .arg("status")
        .assert()
        .failure()
        .stderr(predicate::str::contains("No workspace"));
}

#[test]
fn status_with_cwd_flag() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["-C", temp_dir.path().to_str().unwrap(), "status"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("No workspace"));
}

// =============================================================================
// Session Tests
// =============================================================================

#[test]
fn session_status_without_workspace() {
    let temp_dir = tempfile::tempdir().unwrap();

    // Session status outside a workspace shows "No active session" message
    hif()
        .env("HIF_HOME", temp_dir.path())
        .current_dir(temp_dir.path())
        .args(["session", "status"])
        .assert()
        .success()
        .stdout(predicate::str::contains("no active session"));
}

#[test]
fn session_land_without_session() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .current_dir(temp_dir.path())
        .args(["session", "land"])
        .assert()
        .failure();
}

// =============================================================================
// Error Format Tests
// =============================================================================

#[test]
fn json_error_format() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .current_dir(temp_dir.path())
        .args(["--format", "json", "status"])
        .assert()
        .failure()
        .stderr(predicate::str::contains(r#""status": "error""#))
        .stderr(predicate::str::contains(r#""code":"#));
}

#[test]
fn toon_success_format() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["--format", "toon", "auth", "status"])
        .assert()
        .success()
        .stdout(predicate::str::contains("status: ok"))
        .stdout(predicate::str::contains("action: auth.status"));
}

#[test]
fn toon_error_format() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .current_dir(temp_dir.path())
        .args(["--format", "toon", "status"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("status: error"))
        .stderr(predicate::str::contains("code: no_workspace"));
}

// =============================================================================
// Help JSON Tests (for agents)
// =============================================================================

#[test]
fn help_json_is_valid_json() {
    let output = hif()
        .args(["--help", "--format", "json"])
        .assert()
        .success();

    let stdout = String::from_utf8_lossy(&output.get_output().stdout);
    let parsed: serde_json::Value =
        serde_json::from_str(&stdout).expect("--help --format json should output valid JSON");

    // Verify key fields exist
    assert!(parsed.get("name").is_some());
    assert!(parsed.get("version").is_some());
    assert!(parsed.get("commands").is_some());
    assert!(parsed.get("workflow").is_some());
    assert!(parsed.get("concepts").is_some());
    assert!(parsed.get("error_codes").is_some());
}

#[test]
fn help_json_has_all_commands() {
    let output = hif()
        .args(["--help", "--format", "json"])
        .assert()
        .success();

    let stdout = String::from_utf8_lossy(&output.get_output().stdout);
    let parsed: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    let commands = parsed.get("commands").unwrap().as_object().unwrap();

    // Verify key commands are documented
    assert!(commands.contains_key("auth"));
    assert!(commands.contains_key("checkout"));
    assert!(commands.contains_key("session"));
    assert!(commands.contains_key("status"));
    assert!(commands.contains_key("land"));
    assert!(commands.contains_key("grep"));
}

#[test]
fn format_from_env_uses_toon() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .env("HIF_FORMAT", "toon")
        .current_dir(temp_dir.path())
        .args(["status"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("status: error"))
        .stderr(predicate::str::contains("code: no_workspace"));
}

#[test]
fn checkout_repository_can_come_from_env() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .env("HIF_CHECKOUT_REPOSITORY", "invalid")
        .current_dir(temp_dir.path())
        .args(["checkout"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("Invalid repository"));
}

#[test]
fn sync_strategy_can_come_from_env() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .env("HIF_SYNC_STRATEGY", "invalid")
        .current_dir(temp_dir.path())
        .args(["sync"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("invalid value"));
}

// =============================================================================
// Mount Tests
// =============================================================================

#[test]
fn mount_requires_auth() {
    let temp_dir = tempfile::tempdir().unwrap();
    let mount_dir = temp_dir.path().join("mount-target");

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["mount", "acme/repo", "--path", mount_dir.to_str().unwrap()])
        .assert()
        .failure()
        .stderr(predicate::str::contains("Not authenticated"));
}

#[test]
fn mount_invalid_repository_ref() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["mount", "invalid", "--path", "/tmp/hif-test-mount"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("Invalid repository"));
}

#[test]
fn mount_json_format_requires_auth() {
    let temp_dir = tempfile::tempdir().unwrap();
    let mount_dir = temp_dir.path().join("mount-target");

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args([
            "--format",
            "json",
            "mount",
            "acme/repo",
            "--path",
            mount_dir.to_str().unwrap(),
        ])
        .assert()
        .failure()
        .stderr(predicate::str::contains(r#""status": "error""#))
        .stderr(predicate::str::contains("not_authenticated"));
}

// =============================================================================
// Unmount Tests
// =============================================================================

#[test]
fn unmount_missing_path() {
    let temp_dir = tempfile::tempdir().unwrap();
    let missing = temp_dir.path().join("does-not-exist");

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["unmount", missing.to_str().unwrap()])
        .assert()
        .failure()
        .stderr(predicate::str::contains("Mount path does not exist"));
}

#[test]
fn unmount_not_a_workspace() {
    let temp_dir = tempfile::tempdir().unwrap();
    // Directory exists but has no .hif/ inside
    let mount_dir = temp_dir.path().join("not-a-workspace");
    std::fs::create_dir_all(&mount_dir).unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["unmount", mount_dir.to_str().unwrap()])
        .assert()
        .failure()
        .stderr(predicate::str::contains("Not a hif workspace"));
}

#[test]
fn unmount_valid_workspace() {
    let temp_dir = tempfile::tempdir().unwrap();
    let mount_dir = temp_dir.path().join("my-repo");
    let hif_dir = mount_dir.join(".hif");
    std::fs::create_dir_all(&hif_dir).unwrap();

    // Write a valid manifest
    let manifest = serde_json::json!({
        "version": 1,
        "server": "http://localhost:50051",
        "account": "acme",
        "repository": "app",
        "tree_hash": "",
        "entries": []
    });
    std::fs::write(
        hif_dir.join("manifest.json"),
        serde_json::to_string_pretty(&manifest).unwrap(),
    )
    .unwrap();

    // Also create a dummy file to verify it's preserved
    std::fs::write(mount_dir.join("README.md"), "hello").unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["unmount", mount_dir.to_str().unwrap()])
        .assert()
        .success()
        .stdout(predicate::str::contains("Unmounted"));

    // .hif dir should be removed
    assert!(!hif_dir.exists());
    // Files should remain
    assert!(mount_dir.join("README.md").exists());
}

#[test]
fn unmount_with_remove_flag() {
    let temp_dir = tempfile::tempdir().unwrap();
    let mount_dir = temp_dir.path().join("my-repo-remove");
    let hif_dir = mount_dir.join(".hif");
    std::fs::create_dir_all(&hif_dir).unwrap();

    let manifest = serde_json::json!({
        "version": 1,
        "server": "http://localhost:50051",
        "account": "acme",
        "repository": "app",
        "tree_hash": "",
        "entries": []
    });
    std::fs::write(
        hif_dir.join("manifest.json"),
        serde_json::to_string_pretty(&manifest).unwrap(),
    )
    .unwrap();
    std::fs::write(mount_dir.join("README.md"), "hello").unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["unmount", mount_dir.to_str().unwrap(), "--remove"])
        .assert()
        .success()
        .stdout(predicate::str::contains("Removed"));

    // Entire directory should be gone
    assert!(!mount_dir.exists());
}

#[test]
fn unmount_with_active_session_json_errors() {
    let temp_dir = tempfile::tempdir().unwrap();
    let mount_dir = temp_dir.path().join("my-repo-session");
    let hif_dir = mount_dir.join(".hif");
    std::fs::create_dir_all(&hif_dir).unwrap();

    let manifest = serde_json::json!({
        "version": 1,
        "server": "http://localhost:50051",
        "account": "acme",
        "repository": "app",
        "tree_hash": "",
        "entries": []
    });
    std::fs::write(
        hif_dir.join("manifest.json"),
        serde_json::to_string_pretty(&manifest).unwrap(),
    )
    .unwrap();

    // Create a session file to simulate active session
    std::fs::write(hif_dir.join("session.bin"), b"fake-session-data").unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["--format", "json", "unmount", mount_dir.to_str().unwrap()])
        .assert()
        .failure()
        .stderr(predicate::str::contains("Active session"))
        .stderr(predicate::str::contains("uncommitted changes"));

    // .hif dir should still exist (unmount was blocked)
    assert!(hif_dir.exists());
}

#[test]
fn unmount_json_format_valid_workspace() {
    let temp_dir = tempfile::tempdir().unwrap();
    let mount_dir = temp_dir.path().join("my-repo-json");
    let hif_dir = mount_dir.join(".hif");
    std::fs::create_dir_all(&hif_dir).unwrap();

    let manifest = serde_json::json!({
        "version": 1,
        "server": "http://localhost:50051",
        "account": "acme",
        "repository": "app",
        "tree_hash": "",
        "entries": []
    });
    std::fs::write(
        hif_dir.join("manifest.json"),
        serde_json::to_string_pretty(&manifest).unwrap(),
    )
    .unwrap();

    let output = hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["--format", "json", "unmount", mount_dir.to_str().unwrap()])
        .assert()
        .success();

    let stdout = String::from_utf8_lossy(&output.get_output().stdout);
    let parsed: serde_json::Value = serde_json::from_str(&stdout).expect("should be valid JSON");
    assert_eq!(parsed["status"], "ok");
    assert_eq!(parsed["data"]["removed"], false);
}

// =============================================================================
// Repository Reference Parsing Tests
// =============================================================================

#[test]
fn invalid_repository_ref_in_checkout() {
    let temp_dir = tempfile::tempdir().unwrap();

    // Missing slash
    hif()
        .env("HIF_HOME", temp_dir.path())
        .current_dir(temp_dir.path())
        .args(["checkout", "invalid"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("Invalid repository"));
}

// =============================================================================
// Org Command Tests
// =============================================================================

#[test]
fn org_list_requires_auth() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["org", "list"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("Not authenticated"));
}

#[test]
fn org_list_supports_toon_format() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["--format", "toon", "org", "list"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("status: error"))
        .stderr(predicate::str::contains("code: not_authenticated"));
}

#[test]
fn repository_list_requires_auth() {
    let temp_dir = tempfile::tempdir().unwrap();

    hif()
        .env("HIF_HOME", temp_dir.path())
        .args(["repository", "list", "myorg"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("Not authenticated"));
}
