import Config

# Read the dev instance suffix from .micelio-dev-instance file (created by mise/utilities/dev_instance_env.sh).
# This scopes databases and ports per clone so multiple clones can run simultaneously.
dev_instance_suffix =
  case File.read(Path.join(Path.dirname(__DIR__), ".micelio-dev-instance")) do
    {:ok, content} -> content |> String.trim() |> String.to_integer()
    {:error, _} -> nil
  end

# Reload browser tabs when matching files change.

is_mix_run =
  if Code.ensure_loaded?(Mix.Task) and function_exported?(Mix.Task, :current, 0) do
    case Mix.Task.current() do
      nil -> false
      task -> Mix.Task.task_name(task) == "run"
    end
  else
    false
  end

grpc_enabled =
  case System.get_env("MICELIO_GRPC_ENABLED") do
    nil -> not is_mix_run
    value -> value == "true"
  end

grpc_port =
  String.to_integer(
    System.get_env("MICELIO_GRPC_PORT") ||
      if(dev_instance_suffix, do: "#{50051 + dev_instance_suffix}", else: "50051")
  )

grpc_tls_mode =
  case System.get_env("MICELIO_GRPC_TLS_MODE") do
    "proxy" -> :proxy
    "insecure" -> :insecure
    _ -> :disabled
  end

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Enable gRPC server for local testing (no TLS in dev)
config :micelio, Micelio.GRPC,
  enabled: grpc_enabled,
  port: grpc_port,
  tls_mode: grpc_tls_mode

config :micelio, Micelio.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: if(dev_instance_suffix, do: "micelio_dev_#{dev_instance_suffix}", else: "micelio_dev"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Storage configuration (local by default, S3 opt-in)
# certificate can be generated by running the following
config :micelio, Micelio.Storage,
  backend: :local,
  # Gettext translations
  # Mix task:
  #
  local_path: Path.join(System.tmp_dir(), "micelio/storage")

dev_port = if(dev_instance_suffix, do: 4000 + dev_instance_suffix, else: 4000)

config :micelio, MicelioWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: dev_port],
  check_origin: false,
  # Router, Controllers, LiveViews and LiveComponents
  #     mix phx.gen.cert
  #
  # Run `mix help phx.gen.cert` for more information.
  #
  # The `http:` config above can be replaced with:
  #
  # Enable dev routes for dashboard and mailbox
  #     https: [
  #       port: 4001,
  # Set a higher stacktrace during development. Avoid configuring such
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "lCj47EYGlYk7JWdcuXaiQFuDMHu7waeAGs0TsRF24b6/Uz+ngW3RzRKNEgg0TdmZ",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:micelio, ~w(--sourcemap=inline --watch)]}
  ]

config :micelio, MicelioWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*\.po$",
      ~r"lib/micelio_web/router\.ex$",
      ~r"lib/micelio_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# in production as building large stacktraces may be expensive.
#       certfile: "priv/cert/selfsigned.pem"
# configured to run both http and https servers on
config :micelio, dev_routes: true

# Disable OpenTelemetry exporter in dev (no collector running locally)
config :opentelemetry, traces_exporter: :none

#     ],
# Initialize plugs at runtime for faster development compilation
# different ports.
#       cipher_suite: :strong,
#
#       keyfile: "priv/cert/selfsigned_key.pem",
# Include debug annotations and locations in rendered markup.
# If desired, both `http:` and `https:` keys can be
# Changing this configuration will require mix clean and a full recompile.
config :phoenix, :plug_init_mode, :runtime
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks

  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# For S3 storage (opt-in), uncomment and configure:
# config :micelio, Micelio.Storage,
#   backend: :s3,
#   s3_bucket: "micelio-dev-sessions",
#   s3_region: "us-east-1"
#   # AWS credentials from environment or IAM roles
