//! hif - The hif CLI
//!
//! A forge-first version control system for the agent era.
//!
//! # Architecture
//!
//! The CLI is organized into the following modules:
//!
//! - `cli`: Command-line argument parsing (clap)
//! - `commands`: Command implementations
//! - `config`: Configuration and token management
//! - `core`: Core algorithms (hash, bloom, hlc, tree)
//! - `grpc`: gRPC client for forge communication
//! - `workspace`: Local workspace management
//! - `error`: Error types and handling
//!
//! # Usage
//!
//! ```bash
//! # Authenticate
//! hif auth login
//!
//! # Create a workspace
//! hif checkout myorg/myrepository
//!
//! # Start a session
//! hif session start myorg/myrepository "Add feature X"
//!
//! # Make changes and land
//! hif session land
//! ```
#![recursion_limit = "256"]

mod cache;
mod cdn;
mod cli;
mod commands;
mod config;
mod constants;
mod core;
mod diagnostics;
mod error;
mod grpc;
mod http_client;
mod mountfs;
mod output;
mod workspace;

use clap::builder::styling::{AnsiColor, Color, Style, Styles};
use clap::{ColorChoice, CommandFactory, FromArgMatches};
use cli::{Cli, Commands, OutputMode};
use colored::Colorize;
use config::Config;
use error::Result;
use serde::Serialize;
use std::io::{self, IsTerminal};
use toon_format::encode_default;

fn main() {
    // Build async runtime
    let runtime = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .expect("Failed to create Tokio runtime");

    // Run the CLI
    let exit_code = runtime.block_on(async_main());
    std::process::exit(exit_code);
}

async fn async_main() -> i32 {
    // Check for --help --format json|toon before clap parses (clap exits on --help)
    let args: Vec<String> = std::env::args().collect();
    let has_help = args.iter().any(|a| a == "--help" || a == "-h");
    let has_json = args.iter().any(|a| a == "--json");
    let has_toon = args.iter().any(|a| a == "--toon");
    let has_format = args
        .iter()
        .any(|a| a == "--format" || a.starts_with("--format="));
    let has_docs = args.iter().any(|a| a == "--docs");
    let requested_output_mode = cli::output_mode_from_args(&args);
    let use_structured = requested_output_mode.is_structured();
    let color_enabled = resolve_color_enabled(&args, use_structured);
    configure_color(color_enabled);

    if has_json && has_toon {
        print_error(
            "Choose one output mode: --json or --toon",
            "invalid_output_mode",
            true,
            &[],
        );
        return 1;
    }
    if has_format && (has_json || has_toon) {
        print_error(
            "Choose one output mode selector: use --format or legacy --json/--toon",
            "invalid_output_mode",
            true,
            &[],
        );
        return 1;
    }

    // --docs outputs full documentation for website generation
    if has_docs {
        let docs = cli::generate_docs();
        if requested_output_mode == OutputMode::Toon {
            match encode_default(&docs) {
                Ok(toon) => println!("{}", toon),
                Err(error) => {
                    print_error(
                        &format!("Failed to serialize --docs output as TOON: {}", error),
                        "serialization_error",
                        false,
                        &[],
                    );
                    return 1;
                }
            }
        } else {
            println!("{}", serde_json::to_string_pretty(&docs).unwrap());
        }
        return 0;
    }

    // --help --format json|toon outputs agent-friendly help
    if has_help && use_structured {
        let help = cli::generate_help_json();
        if requested_output_mode == OutputMode::Toon {
            match encode_default(&help) {
                Ok(toon) => println!("{}", toon),
                Err(error) => {
                    print_error(
                        &format!("Failed to serialize help as TOON: {}", error),
                        "serialization_error",
                        false,
                        &[],
                    );
                    return 1;
                }
            }
        } else {
            println!("{}", serde_json::to_string_pretty(&help).unwrap());
        }
        return 0;
    }

    let command = Cli::command()
        .color(color_choice(color_enabled))
        .styles(help_styles(color_enabled));
    let matches = command.get_matches_from(&args);
    let cli = Cli::from_arg_matches(&matches).unwrap_or_else(|err| err.exit());

    if cli.usage_spec {
        let mut usage_command = Cli::command()
            .color(ColorChoice::Never)
            .styles(Styles::plain());

        println!("// @generated by usage-cli from clap metadata");
        clap_usage::generate(&mut usage_command, "hif", &mut io::stdout());
        return 0;
    }

    // Apply --server / --token overrides
    if cli.token.is_some() && cli.server.is_none() {
        print_error(
            "--token requires --server to be specified",
            "invalid_flags",
            use_structured,
            &[],
        );
        return 1;
    }
    if let Some(ref server) = cli.server {
        config::set_server_override(server.clone());
    }
    if let Some(ref token) = cli.token {
        config::set_token_override(token.clone());
    }

    let verbose = cli.verbose;
    let use_structured = cli.output_mode().is_structured();
    if use_structured && color_enabled {
        configure_color(false);
    }

    let original_cwd = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
    if should_capture_diagnostics(cli.command.as_ref()) {
        match diagnostics::init(
            &args,
            &original_cwd,
            cli.cwd.as_deref(),
            verbose,
            output_mode_label(cli.output_mode()),
            cli.command.as_ref().map(command_name),
        ) {
            Ok(info) => {
                if verbose && !use_structured {
                    eprintln!(
                        "info: diagnostics session {} -> {}",
                        info.id,
                        info.dir.display()
                    );
                }
            }
            Err(error) => {
                if verbose && !use_structured {
                    eprintln!("warning: diagnostics disabled: {}", error);
                }
            }
        }
    }

    // Apply --cwd if specified
    if let Err(e) = cli.apply_cwd() {
        diagnostics::log_error(format!("failed to change directory: {}", e));
        print_error(
            &format!("Failed to change directory: {}", e),
            "cwd_error",
            use_structured,
            &[],
        );
        diagnostics::finish(1);
        return 1;
    }

    // Handle no command
    let Some(command) = cli.command else {
        diagnostics::log_error("no command provided");
        print_error(
            "No command provided. Run 'hif --help' for usage.",
            "no_command",
            use_structured,
            &[],
        );
        diagnostics::finish(1);
        return 1;
    };

    output::reset_lifecycle();
    diagnostics::log_info(format!("running command {}", command_name(&command)));

    // Run the command
    match run(command).await {
        Ok(()) => {
            let warnings = output::take_warnings();
            let success_message = output::take_success_message();
            let next_steps = output::take_next_steps();

            if !use_structured {
                if !warnings.is_empty() {
                    output::print_human_warnings(&warnings, false);
                }
                if let Some(message) = success_message {
                    output::print_human_success(&message);
                }
                if !next_steps.is_empty() {
                    output::print_human_next_steps(&next_steps);
                }
            }

            diagnostics::finish(0);
            0
        }
        Err(e) => {
            let warnings = output::take_warnings();
            let _ = output::take_success_message();
            let _ = output::take_next_steps();

            print_error(&e.to_string(), e.code(), use_structured, &warnings);
            if verbose && !use_structured {
                eprintln!("  code: {}", e.code());
            }
            diagnostics::finish(1);
            1
        }
    }
}

#[derive(Serialize)]
struct ErrorEnvelope<'a> {
    status: &'static str,
    code: &'a str,
    message: &'a str,
    #[serde(skip_serializing_if = "Option::is_none")]
    warnings: Option<&'a [String]>,
}

/// Print an error message in the appropriate format.
fn print_error(message: &str, code: &str, use_structured: bool, warnings: &[String]) {
    diagnostics::log_error(format!("error code={} message={}", code, message));
    if use_structured {
        let envelope = ErrorEnvelope {
            status: "error",
            code,
            message,
            warnings: (!warnings.is_empty()).then_some(warnings),
        };

        if output::use_toon() {
            match encode_default(&envelope) {
                Ok(toon) => eprintln!("{}", toon),
                Err(error) => eprintln!(
                    "{}",
                    serde_json::to_string_pretty(&ErrorEnvelope {
                        status: "error",
                        code: "serialization_error",
                        message: &format!("Failed to serialize TOON error output: {}", error),
                        warnings: None,
                    })
                    .unwrap_or_default()
                ),
            }
        } else {
            eprintln!(
                "{}",
                serde_json::to_string_pretty(&envelope).unwrap_or_default()
            );
        }
    } else {
        if !warnings.is_empty() {
            output::print_human_warnings(warnings, true);
        }
        eprintln!("{} {}", "error:".red().bold(), message);
    }
}

fn configure_color(enabled: bool) {
    colored::control::set_override(enabled);
}

fn resolve_color_enabled(args: &[String], use_structured: bool) -> bool {
    if use_structured {
        return false;
    }

    if args.iter().any(|arg| arg == "--no-color") {
        return false;
    }

    if std::env::var_os("NO_COLOR").is_some() {
        return false;
    }

    if let Ok(config) = Config::load() {
        if !config.preferences.color {
            return false;
        }
    }

    let term_is_dumb = std::env::var("TERM")
        .map(|term| term == "dumb")
        .unwrap_or(false);
    let stdout_is_terminal = std::io::stdout().is_terminal();

    stdout_is_terminal && !term_is_dumb
}

fn color_choice(enabled: bool) -> ColorChoice {
    if enabled {
        ColorChoice::Always
    } else {
        ColorChoice::Never
    }
}

fn help_styles(enabled: bool) -> Styles {
    if !enabled {
        return Styles::plain();
    }

    Styles::styled()
        .header(
            Style::new()
                .bold()
                .fg_color(Some(Color::Ansi(AnsiColor::Blue))),
        )
        .usage(
            Style::new()
                .bold()
                .fg_color(Some(Color::Ansi(AnsiColor::Green))),
        )
        .literal(
            Style::new()
                .bold()
                .fg_color(Some(Color::Ansi(AnsiColor::Cyan))),
        )
        .placeholder(Style::new().fg_color(Some(Color::Ansi(AnsiColor::Yellow))))
        .valid(
            Style::new()
                .bold()
                .fg_color(Some(Color::Ansi(AnsiColor::Green))),
        )
        .invalid(
            Style::new()
                .bold()
                .fg_color(Some(Color::Ansi(AnsiColor::Red))),
        )
}

fn output_mode_label(mode: OutputMode) -> &'static str {
    match mode {
        OutputMode::Human => "human",
        OutputMode::Json => "json",
        OutputMode::Toon => "toon",
    }
}

fn command_name(command: &Commands) -> &'static str {
    match command {
        Commands::Auth(_) => "auth",
        Commands::Org(_) => "org",
        Commands::Repository(_) => "repository",
        Commands::Checkout(_) => "checkout",
        Commands::Link(_) => "link",
        Commands::Status => "status",
        Commands::Sync(_) => "sync",
        Commands::Activate(_) => "activate",
        Commands::Skill => "skill",
        Commands::Session(_) => "session",
        Commands::Land(_) => "land",
        Commands::Debug(_) => "debug",
        Commands::Watch(_) => "watch",
        Commands::Show(_) => "show",
        Commands::Tree(_) => "tree",
        Commands::Grep(_) => "grep",
        Commands::Log(_) => "log",
        Commands::Blame(_) => "blame",
        Commands::Diff(_) => "diff",
        Commands::Mount(_) => "mount",
        Commands::MountServe(_) => "mount-serve",
        Commands::Unmount(_) => "unmount",
    }
}

/// Dispatch to the appropriate command handler.
async fn run(command: Commands) -> Result<()> {
    match command {
        // Auth
        Commands::Auth(cmd) => commands::auth::run(cmd).await,

        // Organization & Repository
        Commands::Org(cmd) => commands::org::run(cmd).await,
        Commands::Repository(cmd) => commands::repository::run(cmd).await,

        // Workspace
        Commands::Checkout(cmd) => commands::checkout::run(cmd).await,
        Commands::Link(cmd) => commands::link::run(cmd).await,
        Commands::Status => commands::status::run().await,
        Commands::Sync(cmd) => commands::sync::run(cmd).await,
        Commands::Activate(cmd) => commands::activate::run(cmd).await,
        Commands::Skill => commands::skill::run().await,

        // Sessions
        Commands::Session(cmd) => commands::session::run(cmd).await,
        Commands::Land(cmd) => commands::land::run(cmd).await,
        Commands::Debug(cmd) => commands::debug::run(cmd).await,
        Commands::Watch(cmd) => commands::watch::run(cmd).await,

        // Content (read from forge)
        Commands::Show(cmd) => commands::show::run(cmd).await,
        Commands::Tree(cmd) => commands::tree::run(cmd).await,
        Commands::Grep(cmd) => commands::grep::run(cmd).await,

        // History
        Commands::Log(cmd) => commands::log::run(cmd).await,
        Commands::Blame(cmd) => commands::blame::run(cmd).await,
        Commands::Diff(cmd) => commands::diff::run(cmd).await,

        // Experimental (hidden)
        Commands::Mount(cmd) => commands::mount::run(cmd).await,
        Commands::MountServe(cmd) => mountfs::serve(cmd).await,
        Commands::Unmount(cmd) => commands::unmount::run(cmd).await,
    }
}

fn should_capture_diagnostics(command: Option<&Commands>) -> bool {
    !matches!(
        command,
        Some(Commands::Watch(_)) | Some(Commands::MountServe(_))
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn verify_cli() {
        // Verify the CLI definition is valid
        use clap::CommandFactory;
        Cli::command().debug_assert();
    }
}
